export type TicketSearchQuery = {
  from?: string;
  limit?: string;
  departmentId?: string;
  id?: string;
  ticketNumber?: string;
  subject?: string;
  description?: string;
  status?: string;
  statusType?: string;
  priority?: string;
  email?: string;
  phone?: string;
  channel?: string;
  category?: string;
  assigneeId?: string;
  contactId?: string;
  accountId?: string;
  productId?: string;
  contactName?: string;
  accountName?: string;
  productName?: string;
  tag?: string;
  _all?: string;
  customField1?: string;
  customField2?: string;
  customField3?: string;
  customField4?: string;
  customField5?: string;
  customField6?: string;
  customField7?: string;
  customField8?: string;
  customField9?: string;
  customField10?: string;
  customerResponseTimeRange?: string;
  createdTimeRange?: string;
  modifiedTimeRange?: string;
  dueDateRange?: string;
  sortBy?: string;
};

export type TicketQueryParamKey =
  | 'from'
  | 'limit'
  | 'departmentId'
  | 'id'
  | 'ticketNumber'
  | 'subject'
  | 'description'
  | 'status'
  | 'statusType'
  | 'priority'
  | 'email'
  | 'phone'
  | 'channel'
  | 'category'
  | 'assigneeId'
  | 'contactId'
  | 'accountId'
  | 'productId'
  | 'contactName'
  | 'accountName'
  | 'productName'
  | 'tag'
  | '_all'
  | 'customField1'
  | 'customField2'
  | 'customField3'
  | 'customField4'
  | 'customField5'
  | 'customField6'
  | 'customField7'
  | 'customField8'
  | 'customField9'
  | 'customField10'
  | 'customerResponseTimeRange'
  | 'createdTimeRange'
  | 'modifiedTimeRange'
  | 'dueDateRange'
  | 'sortBy';
